### ISSUE TITLE
search是参数字符串 不是子路径 hash模式返回url不对

### ISSUE THREAD

**Issue by KaneOne** [cool-team-official/cool-admin-vue#10]
https://github.com/cool-team-official/cool-admin-vue/blob/a6b3e9118efc2307de14602752b4c69a1a98cabd/src/core/utils/index.ts#L222

改成从环境参数里获取好了

if (routerMode == "history") {
		url = origin + import.meta.env.BASE_URL + path.substr(1);
	} else {
		url = origin + import.meta.env.BASE_URL + "#" + path;
}

**Comment by icssoa** [comment]
已更新
