### ISSUE TITLE
cool admin 使用"prettier": "^3.0.3",出错无法运行，解决方案很简单如下文

### ISSUE THREAD

**Issue by sdttt1** [cool-team-official/cool-admin-vue#100]
修改cool-admin-vue/build/cool/eps /index.ts，第329行
![微信图片_20231127194734](https://github.com/cool-team-official/cool-admin-vue/assets/30062083/9dcef789-a3b5-4832-b3be-c4ec81af6629)
也就是加以一个await

**Comment by icssoa** [comment]
3以上要加await

> 修改cool-admin-vue/build/cool/eps /index.ts，第329行 ![微信图片_20231127194734](https://private-user-images.githubusercontent.com/30062083/285852152-9dcef789-a3b5-4832-b3be-c4ec81af6629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ3NDIsIm5iZiI6MTcwMTQyNDQ0MiwicGF0aCI6Ii8zMDA2MjA4My8yODU4NTIxNTItOWRjZWY3ODktYTNiNS00ODMyLWIzYmUtYzRlYzgxYWY2NjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZmRjYTVkMTBiZjU1MjQyYWQwMWRlNGUyNmYzNjg3NzNmZjE2OGYxOTFiMzU4ZmZiNDcyNGVmODkzODllNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aQRWaArx_c86MYLetSJ9LLTuqqx_fGjzk4RBw2T_cP0) 也就是加以一个await
