### ISSUE TITLE
cl-search 不能混合搜索吗？

### ISSUE THREAD

**Issue by shoppinglink** [cool-team-official/cool-admin-vue#101]
我看官网的文档2个条件一起搜索，搜索结果也是不正确的（https://admin.cool-js.com/admin/vue/crud/search.html）
![image](https://github.com/cool-team-official/cool-admin-vue/assets/22000025/70d5bff0-33bd-4dd4-be3f-83580fdda759)

**Comment by icssoa** [comment]
> 我看官网的文档2个条件一起搜索，搜索结果也是不正确的（[https://admin.cool-js.com/admin/vue/crud/search.html）](https://admin.cool-js.com/admin/vue/crud/search.html%EF%BC%89) ![image](https://private-user-images.githubusercontent.com/22000025/286812154-70d5bff0-33bd-4dd4-be3f-83580fdda759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ1NDMsIm5iZiI6MTcwMTQyNDI0MywicGF0aCI6Ii8yMjAwMDAyNS8yODY4MTIxNTQtNzBkNWJmZjAtMzNiZC00ZGQ0LWJlM2YtODM1ODBmZGRhNzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5NTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYzMzMzYwM2RhNzdiZDAwZTkwYzQwYjdhZTgzOTFhMDU1MTkzYjQxZjdjMzViMDYwYzI1Mzg5MDZlZGFjZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GwEmzcjUvuavYs6AcssNJcQQsAQ2zU39_A6UAY7OtI0)

可以的，前端只是提交参数。这边是前端模拟的，可能判断错了
