### ISSUE TITLE
Upsert 少 onDelete 的钩子.

### ISSUE THREAD

**Issue by cadcamzy** [cool-team-official/cool-admin-vue#103]
Upsert 少 delete 的钩子.  无法在前端处理一些删除前的校验。

**Comment by icssoa** [comment]
> Upsert 少 delete 的钩子. 无法在前端处理一些删除前的校验。

在 useCrud中配置 [onDelete](https://cool-js.com/admin/vue/crud/crud.html#ondelete-%E5%88%A0%E9%99%A4%E4%BA%8B%E4%BB%B6)
