### ISSUE TITLE
缺少对env.ts中的routermode判断 创建什么模式的路由

### ISSUE THREAD

**Issue by KaneOne** [cool-team-official/cool-admin-vue#11]
https://github.com/cool-team-official/cool-admin-vue/blob/a6b3e9118efc2307de14602752b4c69a1a98cabd/src/router/index.ts#L28

const router = createRouter({
	history: (routerMode=="history")?createWebHistory():createWebHashHistory(),
	routes
});

**Comment by icssoa** [comment]
已更新
