### ISSUE TITLE
前端代码修改后，不能热更新，会刷新页面

### ISSUE THREAD

**Issue by coder-huo** [cool-team-official/cool-admin-vue#115]
修改代码后，都会刷新页面。
这是什么原因呢？
https://github.com/cool-team-official/cool-admin-vue/assets/34032038/e5a6440b-694b-4f23-a961-69254101f714

**Comment by coder-huo** [comment]
修改Web端代码后，不能热更新。
整个页面会刷新，开发效率很低下。
有什么办法解决吗？
<img width="1526" alt="image" src="https://github.com/cool-team-official/cool-admin-vue/assets/34032038/92fbdfe1-f53d-4080-8f53-1dc31b013e8e">

**Comment by icssoa** [comment]
> 修改代码后，都会刷新页面。 这是什么原因呢？ https://github.com/cool-team-official/cool-admin-vue/assets/34032038/e5a6440b-694b-4f23-a961-69254101f714

依赖删了重新安装，.lock也删了。  就行
