### ISSUE TITLE
base/views/menu/index.vue 父节点为空时更新无效

### ISSUE THREAD

**Issue by sdttt1** [cool-team-official/cool-admin-vue#117]
{
			prop: "parentId",
			label: "上级节点",
			hook: {
				submit(value) {
					return value === "" ? null : value;
				}
			},
			component: {
				name: "slot-parentId"
			}
		},

建议改为
		{
			prop: "parentId",
			label: "上级节点",
			hook: {
				submit(value) {
					return value || null;
				}
			},
			component: {
				name: "slot-parentId"
			}
		},

**Comment by icssoa** [comment]
okkk
