### ISSUE TITLE
7/22 提交的代码有bug

### ISSUE THREAD

**Issue by yz1311** [cool-team-official/cool-admin-vue#122]
拉取最新的代码部署会报错
`/cool/bootsrap/module.ts`
```
const list = chain(module.list)
		.map
```

`chain(module.list)`的结果是undefined

**Comment by icssoa** [comment]
> 拉取最新的代码部署会报错 `/cool/bootsrap/module.ts`
> 
> ```
> const list = chain(module.list)
> 		.map
> ```
> 
> `chain(module.list)`的结果是undefined

已修复，拉最新代码
