### ISSUE TITLE
前端打包后，无法运行，无报错

### ISSUE THREAD

**Issue by lst00214** [cool-team-official/cool-admin-vue#127]
![image](https://github.com/user-attachments/assets/0ee710c2-b0bc-45aa-b831-1d66a29d71e9)

前端执行命令：
pnpm run build
pnpm preview

后端执行命令：
pnpm run build
pnpm run start

后端框架：cool-admin-midway

**Comment by cool-team-official** [comment]
部署文档：https://node.cool-admin.com/src/guide/deploy.html

**Comment by icssoa** [comment]
> ![image](https://private-user-images.githubusercontent.com/9882397/358501790-0ee710c2-b0bc-45aa-b831-1d66a29d71e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODgyMjIsIm5iZiI6MTcyNTI4NzkyMiwicGF0aCI6Ii85ODgyMzk3LzM1ODUwMTc5MC0wZWU3MTBjMi1iMGJjLTQ1YWEtYjgzMS0xZDY2YTI5ZDcxZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMTQzODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUyOGJjNGI4YWU5NTZiZTQ4ODg1MjZkMWIxOWE0MDA0NTc2MzkwMTFkYWI1YTkzMjljODJhYmVkZDcxOWRjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LkRZM8jxcDGCShcTH2cKtYqyU2Pt2dXgmmuIAJPNaFo)
> 
> 前端执行命令： pnpm run build pnpm preview
> 
> 后端执行命令： pnpm run build pnpm run start
> 
> 后端框架：cool-admin-midway

拉最新的
