### ISSUE TITLE
演示站打开显示502页面，无法访问

### ISSUE THREAD

**Issue by wushaosen** [cool-team-official/cool-admin-vue#129]
如图
![image](https://github.com/user-attachments/assets/a9603853-b9de-445a-a2d6-3d79084fe582)

**Comment by icssoa** [comment]
> 如图 ![image](https://private-user-images.githubusercontent.com/17971582/365498622-a9603853-b9de-445a-a2d6-3d79084fe582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjcxMzMsIm5iZiI6MTcyOTA2NjgzMywicGF0aCI6Ii8xNzk3MTU4Mi8zNjU0OTg2MjItYTk2MDM4NTMtYjlkZS00NDVhLWEyZDYtM2Q3OTA4NGZlNTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA4MjAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTI1YjlhYjdjZTU1MjkwZmMxMzhjYzcyZDI2OTY2MjM1ZTMwYzU2MjljZTYyYzM4MGJjMzNhMWRmOGNkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORW2kzaBm8dykxOdIFSIDHdpuAOUdq1h1WpUcpOsM9w)

更新中
