### ISSUE TITLE
routerMode设为 hash ts报始终返回false，类型没有重叠错误

### ISSUE THREAD

**Issue by KaneOne** [cool-team-official/cool-admin-vue#13]
https://github.com/cool-team-official/cool-admin-vue/blob/8e1a4a4705261288f1cf5052659b36d993b61077/src/config/env.ts#L6

![image](https://user-images.githubusercontent.com/1954595/113569916-e2fbe180-9645-11eb-98ae-217fcebdc2df.png)

给routerMode指定 String类型后解决
const routerMode: String = "hash";

**Comment by icssoa** [comment]
已更新
