### ISSUE TITLE
vite版本更新依赖到最新报错

### ISSUE THREAD

**Issue by KaneOne** [cool-team-official/cool-admin-vue#21]
vite版本更新依赖到SCSS最新报错
![image](https://user-images.githubusercontent.com/1954595/118217765-b6d74a00-b4a8-11eb-98d8-247a63409802.png)

**Comment by icssoa** [comment]
> vite版本更新依赖到SCSS最新报错
> ![image](https://user-images.githubusercontent.com/1954595/118217765-b6d74a00-b4a8-11eb-98d8-247a63409802.png)

已更新依赖版本
