### ISSUE TITLE
vue3-ts-vite新增按钮下修改弹窗宽度 width无效

### ISSUE THREAD

**Issue by haliuhei** [cool-team-official/cool-admin-vue#24]
https://github.com/cool-team-official/cool-admin-vue/blob/dc22b39fea31872cad95ffe85501a7d5b2eba504/src/cool/modules/base/views/param.vue#L105

如上修改width值，页面没有变化
参考cl-dialog ，title参数也无法生效

**Comment by icssoa** [comment]
> https://github.com/cool-team-official/cool-admin-vue/blob/dc22b39fea31872cad95ffe85501a7d5b2eba504/src/cool/modules/base/views/param.vue#L105
> 
> 如上修改width值，页面没有变化
> 参考cl-dialog ，title参数也无法生效

https://cool-js.com/front/crud/upsert.html 查看 dialog 参数
