### ISSUE TITLE
问题贴： 怎么让upsert组件打开默认全屏， 设置宽度好像也是无效的

### ISSUE THREAD

**Issue by xiusin** [cool-team-official/cool-admin-vue#39]
问题： 怎么让upsert组件打开默认全屏呢， 设置宽度好像也是无效的

有的时候打开组件表单字段太多或者一些其他组件受限于组件宽度，导致无法完美展示内容，要再次点击放大才行。 

求教大佬!!!

**Comment by icssoa** [comment]
> 问题： 怎么让upsert组件打开默认全屏呢， 设置宽度好像也是无效的
> 
> 有的时候打开组件表单字段太多或者一些其他组件受限于组件宽度，导致无法完美展示内容，要再次点击放大才行。
> 
> 求教大佬!!!

设置 dialog 参数
