### ISSUE TITLE
move to vue-echarts@6

### ISSUE THREAD

**Issue by tom-erealm** [cool-team-official/cool-admin-vue#4]
see vue-echarts@6 guide
https://github.com/ecomfe/vue-echarts/blob/main/README.zh-Hans.md#%E8%BF%81%E7%A7%BB%E5%88%B0-v6

**Comment by icssoa** [comment]
已支持

**Comment by tom-erealm** [comment]
006d0dc83a4930cd93f7ceb15ee3f7f15ff01ec1
