### ISSUE TITLE
<cl-add-btn /> 添加到vue里面，但是不显示

### ISSUE THREAD

**Issue by godfery** [cool-team-official/cool-admin-vue#43]
const upsert = reactive<Upsert>({   }）这个也创建了。

请问是什么问题？

**Comment by godfery** [comment]
不好意思打扰了，

因为在菜单里面没有配置权限。

**Comment by pluveto** [comment]
需要添加 add 权限

https://github.com/cool-team-official/cl-admin-crud/blob/main/src/components/add-btn.js
