### ISSUE TITLE
在 src/service/ 下新建文件，为何在$service中没有找到。

### ISSUE THREAD

**Issue by chendeng2017** [cool-team-official/cool-admin-vue#5]
![image](https://user-images.githubusercontent.com/28097670/112413410-1cd20b80-8d5b-11eb-9dd9-a6a5bf3cd960.png)
![image](https://user-images.githubusercontent.com/28097670/112413442-2ce9eb00-8d5b-11eb-9a18-272184868923.png)

**Comment by icssoa** [comment]
模块下的service需要导出
