### ISSUE TITLE
动态路由和js打包分离问题？

### ISSUE THREAD

**Issue by elicip** [cool-team-official/cool-admin-vue#55]
是否cool-admin-vue不支持动态路由按需加载，我看请求页面的时候需要等所有的包文件都加载，这样不科学吧？访问特定路由时按需加载这个部分的包文件是否更好？

**Comment by icssoa** [comment]
模块读取的的时候会全部加载，待优化～

**Comment by elicip** [comment]
@icssoa 希望可以提上日程，现在项目一大初次加载就要占用不少时间，而且在登录页面就把后台的功能逻辑代码加载出来了，也不是很安全

**Comment by icssoa** [comment]
> @icssoa 希望可以提上日程，现在项目一大初次加载就要占用不少时间，而且在登录页面就把后台的功能逻辑代码加载出来了，也不是很安全

这个只是返回实体，而且只有在开发环境下才有

**Comment by icssoa** [comment]
> 是否cool-admin-vue不支持动态路由按需加载，我看请求页面的时候需要等所有的包文件都加载，这样不科学吧？访问特定路由时按需加载这个部分的包文件是否更好？

优化好了

**Comment by elicip** [comment]
已经发布了吗？我用的还是vue2版本，我想看下怎么移植到vue2版本中去

> > 是否cool-admin-vue不支持动态路由按需加载，我看请求页面的时候需要等所有的包文件都加载，这样不科学吧？访问特定路由时按需加载这个部分的包文件是否更好？
> 
> 优化好了
