### ISSUE TITLE
个人中心处更改头像无效

### ISSUE THREAD

**Issue by zhisenyang** [cool-team-official/cool-admin-vue#57]
个人中心处更改头像无效，无报错
![image](https://user-images.githubusercontent.com/3937526/169505130-60932a01-273a-4cb3-adc9-482d5fdd5c19.png)

服务器端采用qiniu上传
![image](https://user-images.githubusercontent.com/3937526/169505284-2f0d82d9-1074-4802-bdd3-ad19af86af37.png)
上传至qiniu成功

![image](https://user-images.githubusercontent.com/3937526/169505691-791ecfb6-9cfd-4e3e-8b01-3fc772383374.png)
但是观测headImg为""，同时并未提交到服务器。

**Comment by icssoa** [comment]
已更新
