### ISSUE TITLE
官网直接访问crud报错

### ISSUE THREAD

**Issue by lhiro** [cool-team-official/cool-admin-vue#59]
### 问题描述
直接访问 https://cool-js.com/admin/vue/crud/crud.html
浏览器报错，且页面空白
![image](https://user-images.githubusercontent.com/20951590/170649905-c25becb2-3b02-433c-b10b-f59647264aba.png)

**Comment by icssoa** [comment]
> ### 问题描述
> 直接访问 https://cool-js.com/admin/vue/crud/crud.html 浏览器报错，且页面空白 ![image](https://user-images.githubusercontent.com/20951590/170649905-c25becb2-3b02-433c-b10b-f59647264aba.png)

暂时从https://cool-js.com进入
