### ISSUE TITLE
打包优化

### ISSUE THREAD

**Issue by microlove1910** [cool-team-official/cool-admin-vue#6]
老铁，能优化下？打包结果要 5M?

**Comment by icssoa** [comment]
你看report, 都是 codemirror、quill 这些的累加。当然你也可以放cdn。主题文件你也可以不放本地呀

**Comment by elicip** [comment]
目前并不会按需加载特定页面的依赖文件，一开始把所有的代码都记载了，很慢啊如果项目工程过大
