### ISSUE TITLE
模块名不能命名为device

### ISSUE THREAD

**Issue by zhisenyang** [cool-team-official/cool-admin-vue#60]
![image](https://user-images.githubusercontent.com/3937526/173401468-2d57aad4-6add-434f-9cfe-a0d0511f8a56.png)

才菜单里点击访问没事，手动刷新浏览器之后会报错

看起来像是匹配dev，然后把dev替换了，所以只剩ice。

**Comment by icssoa** [comment]
> 
和dev代理前缀冲突，改代理或者模块名即可
