### ISSUE TITLE
创建新模块sean报错

### ISSUE THREAD

**Issue by sean5808** [cool-team-official/cool-admin-vue#61]
5.x版本中尝试执行命令（cl create sean）去创建模块报错，4.0版本是没有问题的。

错误提示：
- node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\sean5\Desktop\cool-admin-vue-5.x\src\cool\modules\sean'
    at Object.mkdirSync (node:fs:1334:3)
    at next (C:\Users\sean5\AppData\Roaming\npm\node_modules\cl-admin-cli\bin\cl-create.js:103:6)
    at C:\Users\sean5\AppData\Roaming\npm\node_modules\cl-admin-cli\bin\cl-create.js:156:6
    at FSReqCallback.oncomplete (node:fs:199:5) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'C:\\Users\\sean5\\Desktop\\cool-admin-vue-5.x\\src\\cool\\modules\\sean'

**Comment by icssoa** [comment]
> 5.x版本中尝试执行命令（cl create sean）去创建模块报错，4.0版本是没有问题的。
> 
> 错误提示：
> 
> * node:internal/fs/utils:344
>   throw err;
>   ^
> 
> Error: ENOENT: no such file or directory, mkdir 'C:\Users\sean5\Desktop\cool-admin-vue-5.x\src\cool\modules\sean' at Object.mkdirSync (node:fs:1334:3) at next (C:\Users\sean5\AppData\Roaming\npm\node_modules\cl-admin-cli\bin\cl-create.js:103:6) at C:\Users\sean5\AppData\Roaming\npm\node_modules\cl-admin-cli\bin\cl-create.js:156:6 at FSReqCallback.oncomplete (node:fs:199:5) { errno: -4058, syscall: 'mkdir', code: 'ENOENT', path: 'C:\Users\sean5\Desktop\cool-admin-vue-5.x\src\cool\modules\sean'

5.x 使用 @cool-vue/cli 创建
