### ISSUE TITLE
当操作按钮为 info的时候 bug

### ISSUE THREAD

**Issue by rainscode** [cool-team-official/cool-admin-vue#67]
`const Upsert = useUpsert({
	items: [
		{ label: "名称", prop: "userName", required: true, component: { name: "el-input" } },
		{ label: "接口地址", prop: "apiUrl", required: true, component: { name: "el-input" } },
		{ label: "创建时间", prop: "createTime", component: { name: "el-input" },hidden:(data:{ scope: any; isEdit: boolean; isAdd: boolean }) =>{
			console.log(data)
			return data.isEdit
		}},
	]
});`

当我点击info按钮的时候  isAdd 也为true 
这样会导致一个问题 无法判断 当前是预览还是添加新数据

**Comment by icssoa** [comment]
> `const Upsert = useUpsert({ items: [ { label: "名称", prop: "userName", required: true, component: { name: "el-input" } }, { label: "接口地址", prop: "apiUrl", required: true, component: { name: "el-input" } }, { label: "创建时间", prop: "createTime", component: { name: "el-input" },hidden:(data:{ scope: any; isEdit: boolean; isAdd: boolean }) =>{ console.log(data) return data.isEdit }}, ] });`
> 
> 当我点击info按钮的时候 isAdd 也为true 这样会导致一个问题 无法判断 当前是预览还是添加新数据

`Upsert.value.mode` 用这个判断
