### ISSUE TITLE
cl-admin依赖 href方法未考虑前端在非根目录情况

### ISSUE THREAD

**Issue by KaneOne** [cool-team-official/cool-admin-vue#7]
代码如图所示，只截取了域名部分，没有包含路径
![image](https://user-images.githubusercontent.com/1954595/112752980-524f5100-9008-11eb-984b-3c51413e5a46.png)

**Comment by icssoa** [comment]
cl-admin@1.5.3 已更新

**Comment by KaneOne** [comment]
![image](https://user-images.githubusercontent.com/1954595/112959847-6c0ea680-9176-11eb-9a6b-474cf592e995.png)
href.IndexOf 还是报错
