### ISSUE TITLE
编辑菜单上级节点有时会当前编辑的菜单可选

### ISSUE THREAD

**Issue by imhuso** [cool-team-official/cool-admin-vue#72]
编辑菜单时，上级节点有时不显示正在编辑的菜单，有时会显示。

![image](https://user-images.githubusercontent.com/9276880/199375957-94ac51e4-5c30-425f-9f9f-f826bf168ee4.png)

**Comment by icssoa** [comment]
> 编辑菜单时，上级节点有时不显示正在编辑的菜单，有时会显示。
> 
> ![image](https://user-images.githubusercontent.com/9276880/199375957-94ac51e4-5c30-425f-9f9f-f826bf168ee4.png)

这是上级的，如果最顶级就空
