### ISSUE TITLE
cl-crud中在某些位置写注释时会影响cl-table的max-height值

### ISSUE THREAD

**Issue by wangjun-kk** [cool-team-official/cool-admin-vue#76]
**版本："@cool-vue/crud": "^5.7.1"**
### 加注释前cl-table的max-height为547px
![加注释前](https://md-pic-save.oss-cn-shanghai.aliyuncs.com/typoraImg/table1.png)
### 在此加注释后
![加注释](https://md-pic-save.oss-cn-shanghai.aliyuncs.com/typoraImg/code2.png)
### 加注释后cl-table的max-height为593px
![加注释后](https://md-pic-save.oss-cn-shanghai.aliyuncs.com/typoraImg/table2.png)

**Comment by icssoa** [comment]
安装最新依赖
