### ISSUE TITLE
富文本编辑器全屏有BUG

### ISSUE THREAD

**Issue by calmd0wn** [cool-team-official/cool-admin-vue#77]
富文本编辑器在全屏下，WangEditor 和  Quill 菜单栏显示在屏幕中央偏上，还可以点击操作。
![image](https://user-images.githubusercontent.com/88650982/203914432-4007e996-dc00-4eba-a193-9125582ec619.png)

**Comment by icssoa** [comment]
> 富文本编辑器在全屏下，WangEditor 和 Quill 菜单栏显示在屏幕中央偏上，还可以点击操作。 ![image](https://user-images.githubusercontent.com/88650982/203914432-4007e996-dc00-4eba-a193-9125582ec619.png)

已解决
