### ISSUE TITLE
@cool-vue/crud 升级到^6.0.3   TS类型报错

### ISSUE THREAD

**Issue by Liuxl945** [cool-team-official/cool-admin-vue#80]
![cfa50a7495c11afd45d14dd9522aa74](https://user-images.githubusercontent.com/34531907/222360738-c9d80a7d-9d12-4090-a02e-df13da1feff0.png)
![cd4ba2ae00410dfcf6e726e65060d48](https://user-images.githubusercontent.com/34531907/222360760-f213de38-410f-474a-ad62-b0a1fac12db2.png)

**Comment by icssoa** [comment]
更新即可

**Comment by icssoa** [comment]
> ![cfa50a7495c11afd45d14dd9522aa74](https://user-images.githubusercontent.com/34531907/222360738-c9d80a7d-9d12-4090-a02e-df13da1feff0.png) ![cd4ba2ae00410dfcf6e726e65060d48](https://user-images.githubusercontent.com/34531907/222360760-f213de38-410f-474a-ad62-b0a1fac12db2.png)

更新即可
