### ISSUE TITLE
使用 6.x 的 AI 生成代码时，可能生成带「-」的表格，导致页面报错

### ISSUE THREAD

**Issue by illuz** [cool-team-official/cool-admin-vue#83]
请求到 wss://ai.cool-js.cloud/socket.io 去生成 AI 代码时，可能会生成用拼音生成的表名，导致 service 名是带「-」的，前端调用也有问题。
![image](https://user-images.githubusercontent.com/5182173/231218094-62c639b0-6750-441b-8f6d-529d6c057847.png)
![image](https://user-images.githubusercontent.com/5182173/231218169-ca481e43-fe9c-4a21-8a62-d74620973b40.png)

service 会被注册成驼峰式的，需要使用这种形式才可以正常使用：
![image](https://user-images.githubusercontent.com/5182173/231218745-60ea5009-a7fc-424f-b9ce-30ed4a80b894.png)

建议：
ai 生成时，加上个 prompt，让它表名使用锯齿式的命名方式。

**Comment by icssoa** [comment]
> 请求到 wss://ai.cool-js.cloud/socket.io 去生成 AI 代码时，可能会生成用拼音生成的表名，导致 service 名是带「-」的，前端调用也有问题。 ![image](https://user-images.githubusercontent.com/5182173/231218094-62c639b0-6750-441b-8f6d-529d6c057847.png) ![image](https://user-images.githubusercontent.com/5182173/231218169-ca481e43-fe9c-4a21-8a62-d74620973b40.png)
> 
> service 会被注册成驼峰式的，需要使用这种形式才可以正常使用： ![image](https://user-images.githubusercontent.com/5182173/231218745-60ea5009-a7fc-424f-b9ce-30ed4a80b894.png)
> 
> 建议： ai 生成时，加上个 prompt，让它表名使用锯齿式的命名方式。

已解决
