### ISSUE TITLE
当token过期后点击网页刷新，页面100%会空白一片，空白后再次点击回到登录页

### ISSUE THREAD

**Issue by sdttt1** [cool-team-official/cool-admin-vue#84]

**Comment by sdttt1** [comment]
这个问题我已经解决，错误的原因是刷新页面会再次请求eps，但是token过期了，eps请求就被排入等待队列中去了，导致Service不对了，进而导致user.refreshToken错误。解决方法是修改src/cool/serivce/request.ts。
![image](https://github.com/cool-team-official/cool-admin-vue/assets/30062083/1a4f2ca0-db30-4292-9c5e-b9075f007593)

**Comment by icssoa** [comment]
> 这个问题我已经解决，错误的原因是刷新页面会再次请求eps，但是token过期了，eps请求就被排入等待队列中去了，导致Service不对了，进而导致user.refreshToken错误。解决方法是修改src/cool/serivce/request.ts。 ![image](https://user-images.githubusercontent.com/30062083/242456467-1a4f2ca0-db30-4292-9c5e-b9075f007593.png)

已修复，非常感谢~~~
