### ISSUE TITLE
cl-table组件在一个页面中使用多次，只有最后一次的生效

### ISSUE THREAD

**Issue by falost** [cool-team-official/cool-admin-vue#87]
<img width="432" alt="image" src="https://github.com/cool-team-official/cool-admin-vue/assets/13709107/58322570-9ba0-469e-8ba2-4d2f242bdb98">
<img width="726" alt="image" src="https://github.com/cool-team-official/cool-admin-vue/assets/13709107/b5db8610-1044-490a-b8cd-ff9f329ddca1">
<img width="726" alt="image" src="https://github.com/cool-team-official/cool-admin-vue/assets/13709107/d9be6627-287c-4633-910c-100907d51f3b">

以上是代码和效果

**Comment by icssoa** [comment]
> <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/13709107/246806239-58322570-9ba0-469e-8ba2-4d2f242bdb98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ5NzgsIm5iZiI6MTcwMTQyNDY3OCwicGF0aCI6Ii8xMzcwOTEwNy8yNDY4MDYyMzktNTgzMjI1NzAtOWJhMC00NjllLThiYTItNGQyZjI0MmJkYjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMjRmYmQ1NjkwMTRlZjRmNzI3YmU4N2RkMDU4YmU3MGM2OWQwZmEzMmY0MGFmYjg1YzVkMDcyMzJjNDkzMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qIPuod5aK34v_DwSL_COInu2uOL6MMxnJxsugjb37Is"> <img alt="image" width="726" src="https://private-user-images.githubusercontent.com/13709107/246806253-b5db8610-1044-490a-b8cd-ff9f329ddca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ5NzgsIm5iZiI6MTcwMTQyNDY3OCwicGF0aCI6Ii8xMzcwOTEwNy8yNDY4MDYyNTMtYjVkYjg2MTAtMTA0NC00OTBhLWI4Y2QtZmY5ZjMyOWRkY2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZmZmOWRiYzVkNDIxOGJmZTg4ZDMxZTE0NGY5NThlYTZiNjYwYzA1OTRhZDc0ZTA2NjA2NTYwOTRhNzY4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._mrjGP4Mh0rx2oJZiy3dLrDESrImtqnfIp1jNAzmYg4"> <img alt="image" width="726" src="https://private-user-images.githubusercontent.com/13709107/246806270-d9be6627-287c-4633-910c-100907d51f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ5NzgsIm5iZiI6MTcwMTQyNDY3OCwicGF0aCI6Ii8xMzcwOTEwNy8yNDY4MDYyNzAtZDliZTY2MjctMjg3Yy00NjMzLTkxMGMtMTAwOTA3ZDUxZjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODEwNzRlYTdmYmVmNzAwMjYzNGNlMWZmNWI0OTU5MDMxNjI5M2QxYjM1YmU5YTAyOWUwY2M4N2EyMjAwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U0Vql5eWHP-lZ7DMxjS1c7HRZBekxCl8FnVRnYPmHe4">
> 以上是代码和效果

不要再同一个vue中使用多个crud
