### ISSUE TITLE
cl-table 需要单独使用

### ISSUE THREAD

**Issue by 1032186021** [cool-team-official/cool-admin-vue#88]
cl-table 需要单独使用，，在useTable里面已经配置了autoHeight:false,height,  因为没有搭配使用cl-curd组件，导致在useHeight里面的mitt.on("crud.resize", () => {
        update();
    });这行报错,    mitt 为空，要怎么单独使用cl-table

**Comment by icssoa** [comment]
已解决报错，可以单独使用

> cl-table 需要单独使用，，在useTable里面已经配置了autoHeight:false,height, 因为没有搭配使用cl-curd组件，导致在useHeight里面的mitt.on("crud.resize", () => { update(); });这行报错, mitt 为空，要怎么单独使用cl-table
