### ISSUE TITLE
图表如果不new echarts就会报错

### ISSUE THREAD

**Issue by caolonggang** [cool-team-official/cool-admin-vue#89]
把这段代码去掉就会报错
areaStyle: {
				color: new echarts.graphic.LinearGradient(
					0,
					0,
					0,
					1,
					[
						{
							offset: 0,
							color: "#D1E5FF"
						},
						{
							offset: 1,
							color: "#FFFFFF"
						}
					],
					false
				)
			}

**Comment by icssoa** [comment]
```js
bootstrap(app)
	.then(() => {
		import("echarts");

		app.mount("#app");
	})
	.catch((err) => {
		console.error("COOL-ADMIN 启动失败", err);
	});

```

main.ts 中 import 下

> 把这段代码去掉就会报错 areaStyle: { color: new echarts.graphic.LinearGradient( 0, 0, 0, 1, [ { offset: 0, color: "#D1E5FF" }, { offset: 1, color: "#FFFFFF" } ], false ) }
