### ISSUE TITLE
请问初次加载比较慢，这个能优化吗？

### ISSUE THREAD

**Issue by tomasky** [cool-team-official/cool-admin-vue#90]
请问初次加载比较慢，这个能优化吗？ 其他都还不错，这初次加载至少用了3秒，实在是有些慢了。

**Comment by icssoa** [comment]
单页首次会比较慢，你可能根据情况移除掉不用的模块

> 请问初次加载比较慢，这个能优化吗？ 其他都还不错，这初次加载至少用了3秒，实在是有些慢了。
