### ISSUE TITLE
el-select 组件作为 upsert 的成员，无法把options里的disable属性渲染出来

### ISSUE THREAD

**Issue by xinnix** [cool-team-official/cool-admin-vue#91]
框架默认只渲染label和value

**Comment by xinnix** [comment]
目前的解决方案是，用万能组件

> Form.value?.open({
> 	items: [
> 		{
> 			label: "昵称",
> 			prop: "name",
> 			component: {
> 				name: "slot-name"
> 			}
> 		}
> 	]
> });

**Comment by icssoa** [comment]
okk，优化下

> 框架默认只渲染label和value
