### ISSUE TITLE
7.x访问/sys/menu显示404  ，这是菜单模块

### ISSUE THREAD

**Issue by weikecloud** [cool-team-official/cool-admin-vue#95]
7.x访问/sys/menu显示404  ，这是菜单模块

**Comment by icssoa** [comment]
> 7.x访问/sys/menu显示404 ，这是菜单模块

菜单路径修改了，重新编辑选择下

**Comment by weikecloud** [comment]
无法打开菜单页面，想知道在哪点编辑呢？

**Comment by shoppinglink** [comment]
> 无法打开菜单页面，想知道在哪点编辑呢？

你好，菜单数据保存在数据库。在base_sys_menu表，把id是8的记录的viewPath的值改成modules/base/views/menu.vue（可能每个人的数据不一样，你可以通过‘菜单列表’关键词找出具体数据，然后再进行修改）

**Comment by weikecloud** [comment]
> > 无法打开菜单页面，想知道在哪一点编辑呢？
> 
> 好，菜单数据保存在数据库中。在base_sys_menu表中，把id为8条记录的viewPath的值改成modules/base/views/menu.vue（可能每个人的数据不一样，你可以通过'菜单列表'关键词查找具体数据，然后再进行）

你这是干什么？问题都关闭了解决了
