### ISSUE TITLE
Eps在7.0版本没有类型提示

### ISSUE THREAD

**Issue by thisXiaoWei** [cool-team-official/cool-admin-vue#96]
### 不知道为啥引入进来不生效
![image](https://github.com/cool-team-official/cool-admin-vue/assets/144423706/705aa360-6839-4c90-a61d-7b49772fbf4d)
### **临时解决方案：将eps.d.ts拷贝在src目录下就可以使用**
![image](https://github.com/cool-team-official/cool-admin-vue/assets/144423706/c1249e22-e4a8-419f-87d9-0948c7fdc655)

**Comment by icssoa** [comment]
依赖装完重启下编辑器试试

> ### **环境：windows**
> ### **版本："version": "7.0.0"**
> ### 不知道为啥引入进来不生效
> ![image](https://private-user-images.githubusercontent.com/144423706/277928436-705aa360-6839-4c90-a61d-7b49772fbf4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ3NzAsIm5iZiI6MTcwMTQyNDQ3MCwicGF0aCI6Ii8xNDQ0MjM3MDYvMjc3OTI4NDM2LTcwNWFhMzYwLTY4MzktNGM5MC1hNjFkLTdiNDk3NzJmYmY0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwOTU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDlmMjc2OGMyN2IwZDQ4ZmMxY2JkOWE2YTNkOTQwMWE1ODU5ZmRhZjJjZTZiNzRmZmI3NWM3ZGFlNGViYTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FA9L1vh0geZMrV1CSwDAO84gKBDBZv8POWOBEag18cg)
> 
> ### **临时解决方案：将eps.d.ts拷贝在src目录下就可以使用**
> ![image](https://private-user-images.githubusercontent.com/144423706/277933845-c1249e22-e4a8-419f-87d9-0948c7fdc655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ3NzAsIm5iZiI6MTcwMTQyNDQ3MCwicGF0aCI6Ii8xNDQ0MjM3MDYvMjc3OTMzODQ1LWMxMjQ5ZTIyLWU0YTgtNDE5Zi04N2Q5LTA5NDhjN2ZkYzY1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwOTU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmQ4OWFjNjIzNDQwNGU3YzhiMjc4MjcxN2U5MTE4YTA0MzBmYWU5YmU3NzAxZDNlYzc1YTFkMzYzMDRmM2JlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BoMc69e-hspS0sOmKi2i6k_vLSciB6y8o8HW9XLLiN4)
