### ISSUE TITLE
如何对接后端接口  Eps.service是假数据吗，改了的代码不生效 7.0.0

### ISSUE THREAD

**Issue by ploetiure** [cool-team-official/cool-admin-vue#99]
cool-admin 

version 7.0.0

这个service 和service.base 还有 service.dist node的假数据方法吗，不对接后端一直报错。另外在新增菜单的代码中我已经修改了代码，不管如何刷洗，重新运行，清除缓存，都还报错，而且还是原来的代码，这个地方改了没用吗

![image](https://github.com/cool-team-official/cool-admin-vue/assets/56667263/011f912d-5fb8-4eed-a8b4-17dccd8a6d57)
![image](https://github.com/cool-team-official/cool-admin-vue/assets/56667263/ba287a04-ea62-452d-9869-54965d147690)

**Comment by icssoa** [comment]
build/cool/dist 删了重试，拉最新的代码

> cool-admin
> 
> version 7.0.0
> 
> 这个service 和service.base 还有 service.dist node的假数据方法吗，不对接后端一直报错。另外在新增菜单的代码中我已经修改了代码，不管如何刷洗，重新运行，清除缓存，都还报错，而且还是原来的代码，这个地方改了没用吗
> 
> ![image](https://private-user-images.githubusercontent.com/56667263/283731864-011f912d-5fb8-4eed-a8b4-17dccd8a6d57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ2NzgsIm5iZiI6MTcwMTQyNDM3OCwicGF0aCI6Ii81NjY2NzI2My8yODM3MzE4NjQtMDExZjkxMmQtNWZiOC00ZWVkLWE4YjQtMTdkY2NkOGE2ZDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5NTI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NjM3MDdkNGI4NzY0ZmRmZDE2MDA5NDk3MjU0OTc1OGY4ZjgxZjgzNzdhZTM2MWM0OTU0NGI1YmU4NGQ4ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZ_57UTUHmHh-wZ8WdHUcOf6HsGC5dY6j-8lVEtfEtI) ![image](https://private-user-images.githubusercontent.com/56667263/283731928-ba287a04-ea62-452d-9869-54965d147690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ2NzgsIm5iZiI6MTcwMTQyNDM3OCwicGF0aCI6Ii81NjY2NzI2My8yODM3MzE5MjgtYmEyODdhMDQtZWE2Mi00NTJkLTk4NjktNTQ5NjVkMTQ3NjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5NTI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YmEwMDRlYTAxZTliM2JhZTUzMDNiYTdjZWVlODM3YjFkNzJmMDlkM2QwODZkOWIwZWJlZmRmNmRlZTkxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.is4US6x7HkeRPtrkp7L8c1BVhge1uA9dUY30rJFFoL0)
